# en el link https://kubernetes.io/es/docs/concepts/configuration/configmap/ buscamos secrets y copiamos el siguiente ejemplo
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  #utilizamos el Base64 para encriptar la contraseña en el siguiente link= https://codebeautify.org/base64-encode
  #en el bash se puede utilizar el comando= echo -n 'contraseña' | base64
  JWT_SECRET: nombredelabasededatos
  

