#link de docker hub  de la imagen a utilizar en el backend=  https://hub.docker.com/r/klerith/k8s-teslo-backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: klerith/k8s-teslo-backend
        ports:
        - containerPort: 3000
      env:
      - name: APP_VERSION
        value: "1.0.0"
      - name: PORT
        value: "3000"
      - name: STAGE
        value: "prod"
      - name: DB_NAME
        valueFrom:
          configMapKeyRef:
            name: postgres-configmap
            key: BD_NAME    
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: postgres-configmap
            key: BD_HOST
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: postgres-configmap
            key: BD_PORT      

      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: DB_USER

      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: backend-secrets
            key: JWT_SECRET      
                 
---
#buscamos services en el siguiente link= https://kubernetes.io/es/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
